CREATE DATABASE DDL16_18;
USE DDL16_18; 

CREATE TABLE Medicos (
 id INT PRIMARY KEY AUTO_INCREMENT UNIQUE,
 nome VARCHAR (120) NOT NULL,
 crm VARCHAR(20) NOT NULL UNIQUE,
 especialidade VARCHAR(80) NOT NULL,
 telefone VARCHAR(20) NOT NULL UNIQUE
); 

CREATE TABLE Pacientes (
 id INT PRIMARY KEY AUTO_INCREMENT UNIQUE,
 nome VARCHAR (120) NOT NULL,
 cpf CHAR(11) NOT NULL UNIQUE,
 dataNascimento DATE NOT NULL,
 telefone VARCHAR(20) NOT NULL UNIQUE
); 

CREATE TABLE Consultas (
id INT PRIMARY KEY AUTO_INCREMENT UNIQUE,
medico_id INT,
paciente_id INT,
data_hora TIMESTAMP,
status_consulta VARCHAR(20) NOT NULL,
FOREIGN KEY (medico_id) REFERENCES Medicos(id),
FOREIGN KEY (paciente_id) REFERENCES Pacientes(id)
);