CREATE DATABASE DDL1_4;
USE DDL1_4;

CREATE TABLE Clientes (
    id INT PRIMARY KEY AUTO_INCREMENT UNIQUE,
    nome VARCHAR (100) NOT NULL,
    email VARCHAR(120)  NOT NULL UNIQUE,
    data_cadastro DATETIME DEFAULT CURRENT_TIMESTAMP,
    telefone  VARCHAR(20)  NOT NULL
); 


CREATE TABLE Produtos(
 id INT PRIMARY KEY AUTO_INCREMENT UNIQUE,
 nome VARCHAR(120) NOT NULL,
 preco DECIMAL(10,2) NOT NULL,
 categoria VARCHAR(60) NOT NULL,
 estoque INT NOT NULL
); 
  
CREATE TABLE Pedidos ( 
	id INT PRIMARY KEY AUTO_INCREMENT UNIQUE,
    id_clientes INT,
    data_pedido DATETIME DEFAULT CURRENT_TIMESTAMP,
    valor_total DECIMAL(12,2) NOT NULL,
	status_pedido VARCHAR(20) NOT NULL,
    FOREIGN KEY (id_clientes) REFERENCES Clientes(id)
);


CREATE TABLE Funcionarios (
    id INT PRIMARY KEY AUTO_INCREMENT UNIQUE,
    nome VARCHAR(100) NOT NULL,
    cpf VARCHAR(11) NOT NULL UNIQUE,
    cargo VARCHAR(60) NOT NULL,
    salario DECIMAL(10 , 2 ) NOT NULL
);  

