CREATE DATABASE DDL5_12;
USE DDL5_12; 

CREATE TABLE Cursos (
    id INT PRIMARY KEY AUTO_INCREMENT UNIQUE,
    nome VARCHAR(120) NOT NULL,
    carga_horaria INT NOT NULL,
    modalidade VARCHAR(30) NOT NULL,
    ativo BOOLEAN NOT NULL
);

CREATE TABLE Alunos (
    id INT PRIMARY KEY AUTO_INCREMENT UNIQUE,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(120) NOT NULL UNIQUE,
    data_matricula DATETIME DEFAULT CURRENT_TIMESTAMP,
    curso_id INT,
    FOREIGN KEY (curso_id)
        REFERENCES Cursos (id)
); 

CREATE TABLE Notas (
id INT PRIMARY KEY AUTO_INCREMENT UNIQUE,
aluno_id INT,
disciplina VARCHAR(80) NOT NULL,
avaliacao VARCHAR(40) NOT NULL,
nota DECIMAL(4,2) NOT NULL,
FOREIGN KEY (aluno_id) REFERENCES Alunos(id)
);

CREATE TABLE Departamentos(
id INT PRIMARY KEY AUTO_INCREMENT UNIQUE,
codigo CHAR(5) UNIQUE NOT NULL,
nome VARCHAR(100) NOT NULL,
centro_custo VARCHAR(20) NOT NULL,
ativo BOOLEAN NOT NULL
);


CREATE TABLE Editoras(
id INT PRIMARY KEY AUTO_INCREMENT UNIQUE,
nome VARCHAR(150) NOT NULL,
cnpj CHAR(14) UNIQUE NOT NULL,
cidade VARCHAR(80) NOT NULL,
uf CHAR(2) NOT NULL
);

CREATE TABLE Livros(
id INT PRIMARY KEY AUTO_INCREMENT UNIQUE,
id_editora INT,
isbn CHAR(13) UNIQUE UNIQUE NOT NULL,
titulo VARCHAR(150) NOT NULL,
autor VARCHAR(120) NOT NULL,
ano INT NOT NULL,
FOREIGN KEY (id_editora) REFERENCES Editoras(id)
);


CREATE TABLE Autores(
id INT PRIMARY KEY AUTO_INCREMENT UNIQUE,
nome VARCHAR(120) NOT NULL,
nacionalidade VARCHAR(60) NOT NULL,
email VARCHAR(120) UNIQUE NOT NULL,
data_nascimento DATE NOT NULL
);

CREATE TABLE Emprestimos(
id INT PRIMARY KEY AUTO_INCREMENT UNIQUE,
aluno_id INT,
livro_id INT NOT NULL,
data_saida DATETIME DEFAULT CURRENT_TIMESTAMP,
data_devolucao DATE NOT NULL
);

